feat: add release build script

diff --git a/.github/workflows/build-unitycloud.yml b/.github/workflows/build-unitycloud.yml
--- a/.github/workflows/build-unitycloud.yml
+++ b/.github/workflows/build-unitycloud.yml
@@ -4,6 +4,8 @@ on:
   push:
     branches:
       - main
+    tags:
+      - 'v*'
   workflow_dispatch:
     inputs:
       profile:
@@ -39,7 +41,7 @@ jobs:
     outputs:
       commit_sha: ${{ steps.get_commit_sha.outputs.commit_sha }}
       options: ${{ steps.get_options.outputs.options }}
-      version: ${{ github.event.inputs.version || inputs.version || steps.get_version.outputs.full_version }}
+      version: ${{ steps.get_version.outputs.full_version }}
       clean_build: ${{ steps.set_defaults.outputs.clean_build }}
       cache_strategy: ${{ steps.set_defaults.outputs.cache_strategy }}
     steps:
@@ -58,13 +60,12 @@ jobs:
           echo "Ref from Pull Request: ${{ github.event.pull_request.head.sha }}"
           echo "Full Commit from git rev-parse: $(git rev-parse $GITHUB_SHA)"
           echo "HEAD Commit: $(git rev-parse HEAD)"
-      
-      #      - name: Get version
-      #        id: get_version
-      #        if: ${{ github.event.inputs.version == '' && inputs.version == '' }}
-      #        uses: ./.github/actions/version
-      #        with:
-      #          commit_sha: ${{ steps.get_commit_sha.outputs.commit_sha }}
+          
+      - name: Get version
+        id: get_version
+        uses: ./.github/actions/version
+        with:
+          commit_sha: ${{ steps.get_commit_sha.outputs.commit_sha }}
 
       - name: Set default values
         id: set_defaults
@@ -74,13 +75,6 @@ jobs:
             clean_build=${{ github.event.inputs.clean_build }}
           elif [ "${{ inputs.clean_build }}" ]; then
             clean_build=${{ inputs.clean_build }}
-          else
-            clean_build=false
-            if [ "${{ github.event_name }}" == "pull_request" ]; then
-              echo "Checking PR labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}"
-              # Proper label check with spaces
-              clean_build=$(echo "${{ join(github.event.pull_request.labels.*.name, ' ') }}" | grep -qw 'clean-build' && echo true || echo false)
-            fi
           fi
           echo "Set clean_build to: $clean_build"
           echo "clean_build=${clean_build}" >> $GITHUB_OUTPUT
@@ -94,16 +88,6 @@ jobs:
           fi
           echo "Set cache_strategy to: $cache_strategy"
           echo "cache_strategy=${cache_strategy}" >> $GITHUB_OUTPUT
-
-          if [ "${{ github.event.inputs.install_source }}" ]; then
-            install_source=${{ github.event.inputs.install_source }}
-          elif [ "${{ inputs.install_source }}" ]; then
-            install_source=${{ inputs.install_source }}
-          else
-            install_source='launcher'
-          fi
-          echo "Set install_source to: $install_source"
-          echo "install_source=${install_source}" >> $GITHUB_OUTPUT
 
       - name: Get BuildOptions
         id: get_options
@@ -140,7 +124,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
+          ref: ${{ github.ref_name }}
 
       - name: Setup python
         uses: actions/setup-python@v5
@@ -176,16 +160,15 @@ jobs:
           BUILD_OPTIONS: ${{ needs.prebuild.outputs.options }}
           CLEAN_BUILD: ${{ needs.prebuild.outputs.clean_build }}
           CACHE_STRATEGY: ${{ needs.prebuild.outputs.cache_strategy }}
-          IS_RELEASE_BUILD: ${{ inputs.is_release_build }}
-          # TAG_VERSION: ${{ inputs.tag_version }} TODO
-          TAG_VERSION: 0.0.1-test
+          IS_RELEASE_BUILD: ${{ startsWith(github.ref, 'refs/tags/') }}
+          TAG_VERSION: ${{ needs.prebuild.outputs.version }}
           #Possible values: { none, library, workspace, inherit }
           # Any ENV variables starting with "PARAM_" will be passed to Unity without the prefix
           # (The "PARAM_" prefix exists to allow any future values config-free)
           # e.g.: PARAM_ALLOW_DEBUG -> In Unity will be available as "ALLOW_DEBUG"
           # e.g.: Editor.CloudBuild.Parameters["ALLOW_DEBUG"]
-          # PARAM_BUILD_VERSION: ${{ needs.prebuild.outputs.version }} TODO
-          PARAM_BUILD_VERSION: 0.0.1-test
+          PARAM_BUILD_VERSION: ${{ needs.prebuild.outputs.version }}
+          #PARAM_BUILD_VERSION: 0.0.1-test
           PARAM_UNITY_EXTRA_PARAMS: '-disable-assembly-updater'
 
       - name: Set artifact name
@@ -201,6 +184,34 @@ jobs:
           path: |
             build
           if-no-files-found: error
+
+      - name: Zip Build Output
+        if: ${{ startsWith(github.ref, 'refs/tags/') }}
+        run: zip -r build.zip build/
+
+      - name: Create GitHub Release
+        if: ${{ startsWith(github.ref, 'refs/tags/') }}
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ github.ref_name }}
+          release_name: Release ${{ github.ref_name }}
+          body: Release for ${{ github.ref_name }}
+          draft: false
+          prerelease: false
+
+      - name: Upload Release Asset
+        if: ${{ startsWith(github.ref, 'refs/tags/') }}
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: build.zip
+          asset_name: aang-renderer-${{ github.ref_name }}.zip
+          asset_content_type: application/zip
 
       - name: Set SHA, branch, and build prefix
         run: |
@@ -224,7 +235,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: web_${{ needs.prebuild.outputs.install_source }}_unity_log
+          name: web_unity_log
           path: unity_cloud_log.log
           if-no-files-found: error
 
@@ -236,20 +247,8 @@ jobs:
       - name: Extract and display errors
         if: always()
         run: |
-          echo "=== Extracted Errors for ${{ matrix.target }} ${{ needs.prebuild.outputs.install_source }} ==="
-          grep -iE "error c|fatal" unity_cloud_log.log | sed 's/^/\x1b[31m/' | sed 's/$/\x1b[0m/' || echo "No 'error c' or 'fatal' errors found in ${{ matrix.target }} log."
-
-      - name: Generate Shader Compilation Report
-        shell: pwsh
-        run: |
-          ./scripts/Generate-ShaderReport.ps1 -InputLog "unity_cloud_log.log" -OutputReport "shader_compilation_report.log"
-
-      - name: Upload Shader Compilation Report
-        uses: actions/upload-artifact@v4
-        with:
-          name: web_${{ needs.prebuild.outputs.install_source }}_shader_compilation_report
-          path: shader_compilation_report.log
-          if-no-files-found: warn
+          echo "=== Extracted Errors ==="
+          grep -iE "error c|fatal" unity_cloud_log.log | sed 's/^/\x1b[31m/' | sed 's/$/\x1b[0m/' || echo "No 'error c' or 'fatal' errors found in log."
 
       # Will run on cancel or timeout only
       - name: Cancel Unity Cloud build
